import 'package:dio/dio.dart';

import '../../../core/appColor.dart';

class Opportunitydataprovider {
  Future<dynamic> allOpportunityData() async {
    return await DioHelper.getData(
        url: "https://api.cfc.sa/api/list_campaign", header: {});
  }

  Future<dynamic> myOpportunityData() async {
    return await DioHelper.getData(
        url: "https://api.cfc.sa/api/user_campaign/5", header: {});
  }

  Future<dynamic> myOpportunityAttachment(int id) async {
    return await DioHelper.getData(
        url: "https://api.cfc.sa/api/get_campaign_attachements/${id}",
        header: {});
  }

  Future<dynamic> myOpportunityDetails(int id) async {
    return await DioHelper.getData(
        url: "https://api.cfc.sa/api/opportunity_detail/$id", header: {});
  }

  Future<dynamic> watheqIqama(String iqama, String date) async {
    return await DioHelper.getData(
        url: "https://api.cfc.sa/api/yaqenIqama?iqama=$iqama&birthDateG=$date",
        header: {});
  }

  Future<dynamic> watheqsaudi(String iqama, String date) async {
    return await DioHelper.getData(
        url: "https://api.cfc.sa/api/yaqeensaudi?nin=$iqama&dateString=$date",
        header: {});
  }

  Future<dynamic> modifyKyc(
      String email,
      String mobileNumber,
      String matiralStatus,
      String familyNumber,
      String gender,
      String education,
      String region,
      String jobStatus,
      String nationalityLocation,
      String identityType,
      String nationality,
      String bank,
      String date,
      String idNumber,
      String iban,
      bool income,
      bool one,
      bool two,
      bool three,
      bool four,
      bool five,
      bool six,
      bool seven,
      bool eight,
      bool wkaleh,
      bool selectedAnswer,
      String arabicName,
      String englishName) async {



             return  await DioHelper.postData(
                    url: "https://api.cfc.sa/api/modify_userkyc",
                    data:FormData.fromMap({
                          'nationality_id': idNumber,
                          'field[0][id]': '6',
                          'field[0][kyc_id]': '10',
                          'field[0][type]': '2',
                          'field[0][info_type]': '20',
                          'field[0][title]': 'البريد الالكتروني',
                          'field[0][length]': '50',
                          'field[0][mandatory]': '1',
                          'field[0][status]': '1',
                          'field[0][position]': '1',
                          'field[0][user_kyc_id]': '7875',
                          'field[0][value]': email,
                          'field[0][required]': 'false',
                          'field[0][invalid]': 'false',
                          'field[0][error_message]': '',
                          'field[1][id]': '8',
                          'field[1][kyc_id]': '10',
                          'field[1][type]': '4',
                          'field[1][info_type]': '20',
                          'field[1][title]': 'رقم الجوال',
                          'field[1][length]': '10',
                          'field[1][mandatory]': '1',
                          'field[1][status]': '1',
                          'field[1][position]': '2',
                          'field[1][user_kyc_id]': '7876',
                          'field[1][value]': mobileNumber,
                          'field[1][required]': 'false',
                          'field[1][invalid]': 'false',
                          'field[1][error_message]': '',
                          'field[2][id]': '13',
                          'field[2][kyc_id]': '1',
                          'field[2][type]': '14',
                          'field[2][info_type]': '1',
                          'field[2][title]': 'الحالة الاجتماعية',
                          'field[2][length]': '',
                          'field[2][mandatory]': '1',
                          'field[2][status]': '1',
                          'field[2][position]': '11',
                          'field[2][user_kyc_id]': '7877',
                          'field[2][value]': matiralStatus,
                          'field[2][required]': 'false',
                          'field[2][invalid]': 'false',
                          'field[3][id]': '14',
                          'field[3][kyc_id]': '1',
                          'field[3][type]': '6',
                          'field[3][info_type]': '1',
                          'field[3][title]': 'عدد افراد الاسرة',
                          'field[3][length]': '2',
                          'field[3][mandatory]': '1',
                          'field[3][status]': '1',
                          'field[3][position]': '12',
                          'field[3][user_kyc_id]': '7878',
                          'field[3][value]': familyNumber,
                          'field[3][required]': 'false',
                          'field[3][invalid]': 'false',
                          'field[4][id]': '166',
                          'field[4][kyc_id]': '1',
                          'field[4][type]': '11',
                          'field[4][info_type]': '1',
                          'field[4][title]': 'الجنس',
                          'field[4][length]': '',
                          'field[4][mandatory]': '1',
                          'field[4][status]': '1',
                          'field[4][position]': '12',
                          'field[4][user_kyc_id]': '7879',
                          'field[4][value]':gender,
                          'field[4][required]': 'true',
                          'field[4][invalid]': 'false',
                          'field[5][id]': '151',
                          'field[5][kyc_id]': '1',
                          'field[5][type]': '15',
                          'field[5][info_type]': '1',
                          'field[5][title]': 'التحصيل الاكاديمي',
                          'field[5][length]': '',
                          'field[5][mandatory]': '1',
                          'field[5][status]': '1',
                          'field[5][position]': '13',
                          'field[5][user_kyc_id]': '7880',
                          'field[5][value]': education,
                          'field[5][required]': 'false',
                          'field[5][invalid]': 'false',
                          'field[6][id]': '152',
                          'field[6][kyc_id]': '1',
                          'field[6][type]': '16',
                          'field[6][info_type]': '1',
                          'field[6][title]': 'الحالة الوظيفية',
                          'field[6][length]': '',
                          'field[6][mandatory]': '1',
                          'field[6][status]': '1',
                          'field[6][position]': '13',
                          'field[6][user_kyc_id]': '7881',
                          'field[6][value]': jobStatus,
                          'field[6][required]': 'false',
                          'field[6][invalid]': 'false',
                          'field[7][id]': '162',
                          'field[7][kyc_id]': '1',
                          'field[7][type]': '1',
                          'field[7][info_type]': '1',
                          'field[7][title]': 'العنوان الوطني',
                          'field[7][length]': '8',
                          'field[7][mandatory]': '0',
                          'field[7][status]': '1',
                          'field[7][position]': '14',
                          'field[7][user_kyc_id]': '7882',
                          'field[7][value]': nationalityLocation,
                          'field[7][required]': 'false',
                          'field[7][invalid]': 'false',
                          'field[8][id]': '163',
                          'field[8][kyc_id]': '1',
                          'field[8][type]': '21',
                          'field[8][info_type]': '1',
                          'field[8][title]': 'المنطقة',
                          'field[8][length]': '',
                          'field[8][mandatory]': '1',
                          'field[8][status]': '1',
                          'field[8][position]': '15',
                          'field[8][user_kyc_id]': '7883',
                          'field[8][value]': region,
                          'field[8][required]': 'false',
                          'field[8][invalid]': 'false',
                          'field[9][id]': '131',
                          'field[9][kyc_id]': '2',
                          'field[9][type]': '10',
                          'field[9][info_type]': '19',
                          'field[9][title]': 'هوية المسجل',
                          'field[9][length]': '',
                          'field[9][mandatory]': '1',
                          'field[9][status]': '1',
                          'field[9][position]': '1',
                          'field[9][user_kyc_id]': '7884',
                          'field[9][value]': identityType,
                          'field[9][required]': 'false',
                          'field[9][invalid]': 'false',
                          'field[10][id]': '135',
                          'field[10][kyc_id]': '2',
                          'field[10][type]': '6',
                          'field[10][info_type]': '19',
                          'field[10][title]': 'رقم الهوية',
                          'field[10][length]': '10',
                          'field[10][mandatory]': '1',
                          'field[10][status]': '1',
                          'field[10][position]': '2',
                          'field[10][user_kyc_id]': '7885',
                          'field[10][value]': idNumber,
                          'field[10][required]': 'false',
                          'field[10][invalid]': 'false',
                          'field[11][id]': '132',
                          'field[11][kyc_id]': '2',
                          'field[11][type]': '17',
                          'field[11][info_type]': '19',
                          'field[11][title]': 'سنة الميلاد هجري',
                          'field[11][length]': '',
                          'field[11][mandatory]': '0',
                          'field[11][status]': '1',
                          'field[11][position]': '3',
                          'field[11][user_kyc_id]': '7886',
                          'field[11][value]':date,
                          'field[11][required]': 'false',
                          'field[11][invalid]': 'false',
                          'field[12][id]': '133',
                          'field[12][kyc_id]': '2',
                          'field[12][type]': '18',
                          'field[12][info_type]': '19',
                          'field[12][title]': 'الشهر هجري',
                          'field[12][length]': '100',
                          'field[12][mandatory]': '0',
                          'field[12][status]': '1',
                          'field[12][position]': '4',
                          'field[12][user_kyc_id]': '7887',
                          'field[12][value]': '',
                          'field[12][required]': 'false',
                          'field[12][invalid]': 'false',
                          'field[13][id]': '134',
                          'field[13][kyc_id]': '2',
                          'field[13][type]': '19',
                          'field[13][info_type]': '19',
                          'field[13][title]': 'يوم الولادة هجري',
                          'field[13][length]': '',
                          'field[13][mandatory]': '0',
                          'field[13][status]': '1',
                          'field[13][position]': '4',
                          'field[13][user_kyc_id]': '7888',
                          'field[13][value]': '',
                          'field[13][required]': 'false',
                          'field[13][invalid]': 'false',
                          'field[14][id]': '136',
                          'field[14][kyc_id]': '2',
                          'field[14][type]': '7',
                          'field[14][info_type]': '19',
                          'field[14][title]': 'تاريخ الولادة',
                          'field[14][length]': '',
                          'field[14][mandatory]': '0',
                          'field[14][status]': '1',
                          'field[14][position]': '6',
                          'field[14][user_kyc_id]': '7889',
                          'field[14][value]': date,
                          'field[14][required]': 'false',
                          'field[14][invalid]': 'false',
                          'field[15][id]': '137',
                          'field[15][kyc_id]': '2',
                          'field[15][type]': '1',
                          'field[15][info_type]': '19',
                          'field[15][title]': 'الاسم بالعربية',
                          'field[15][length]': '100',
                          'field[15][mandatory]': '0',
                          'field[15][status]': '1',
                          'field[15][position]': '7',
                          'field[15][user_kyc_id]': '7890',
                          'field[15][value]': arabicName,
                          'field[15][required]': 'false',
                          'field[15][invalid]': 'false',
                          'field[16][id]': '138',
                          'field[16][kyc_id]': '2',
                          'field[16][type]': '1',
                          'field[16][info_type]': '19',
                          'field[16][title]': 'الاسم بالانجليزي',
                          'field[16][length]': '100',
                          'field[16][mandatory]': '0',
                          'field[16][status]': '1',
                          'field[16][position]': '8',
                          'field[16][user_kyc_id]': '7891',
                          'field[16][value]': englishName,
                          'field[16][required]': 'false',
                          'field[16][invalid]': 'false',
                          'field[17][id]': '37',
                          'field[17][kyc_id]': '4',
                          'field[17][type]': '1',
                          'field[17][info_type]': '2',
                          'field[17][title]': 'رقم الحساب البنكي-الايبان',
                          'field[17][length]': '24',
                          'field[17][mandatory]': '1',
                          'field[17][status]': '1',
                          'field[17][position]': '1',
                          'field[17][user_kyc_id]': '7892',
                          'field[17][value]': iban,
                          'field[17][required]': 'false',
                          'field[17][invalid]': 'false',
                          'field[18][id]': '121',
                          'field[18][kyc_id]': '4',
                          'field[18][type]': '12',
                          'field[18][info_type]': '2',
                          'field[18][title]': 'البنك',
                          'field[18][length]': '',
                          'field[18][mandatory]': '1',
                          'field[18][status]': '1',
                          'field[18][position]': '2',
                          'field[18][user_kyc_id]': '7893',
                          'field[18][value]': bank,
                          'field[18][required]': 'false',
                          'field[18][invalid]': 'false',
                          'field[19][id]': '35',
                          'field[19][kyc_id]': '4',
                          'field[19][type]': '8',
                          'field[19][info_type]': '2',
                          'field[19][title]': 'الدخل السنوي اكبر من 100,000 ريال',
                          'field[19][length]': '',
                          'field[19][mandatory]': '1',
                          'field[19][status]': '1',
                          'field[19][position]': '4',
                          'field[19][user_kyc_id]': '7894',
                          'field[19][value]':income?'1':'0',
                          'field[19][required]': 'false',
                          'field[19][invalid]': 'false',
                          'field[20][id]': '34',
                          'field[20][kyc_id]': '3',
                          'field[20][type]': '8',
                          'field[20][info_type]': '20',
                          'field[20][title]': 'هل سبق لك العمل في القطاع المالي خلال السنوات الخمس الماضية ؟',
                          'field[20][length]': '',
                          'field[20][mandatory]': '1',
                          'field[20][status]': '1',
                          'field[20][position]': '1',
                          'field[20][user_kyc_id]': '7895',
                          'field[20][value]': one?'1':'0',
                          'field[20][required]': 'false',
                          'field[20][invalid]': 'false',
                          'field[21][id]': '154',
                          'field[21][kyc_id]': '3',
                          'field[21][type]': '8',
                          'field[21][info_type]': '20',
                          'field[21][title]': 'هل لديك أي خبرات عملية أخرى ذات الصة بالقطاع المالي ؟',
                          'field[21][length]': '',
                          'field[21][mandatory]': '1',
                          'field[21][status]': '1',
                          'field[21][position]': '2',
                          'field[21][user_kyc_id]': '7896',
                          'field[21][value]': two?'1':'0',
                          'field[21][required]': 'false',
                          'field[21][invalid]': 'false',
                          'field[22][id]': '155',
                          'field[22][kyc_id]': '3',
                          'field[22][type]': '8',
                          'field[22][info_type]': '20',
                          'field[22][title]': 'هل انت عضو مجلس ادارة او لجنة مراجعة او احد كبار التنفيذيين في شركة مدرجة؟',
                          'field[22][length]': '',
                          'field[22][mandatory]': '1',
                          'field[22][status]': '1',
                          'field[22][position]': '3',
                          'field[22][user_kyc_id]': '7897',
                          'field[22][value]': three?'1':'0',
                          'field[22][required]': 'false',
                          'field[22][invalid]': 'false',
                          'field[23][id]': '156',
                          'field[23][kyc_id]': '3',
                          'field[23][type]': '8',
                          'field[23][info_type]': '20',
                          'field[23][title]': 'هل انت ذو علاقة بعضو مجلس ادارة او لجنة مراجعة او احد كبار التنفيذيين في شركة مدرجة؟',
                          'field[23][length]': '',
                          'field[23][mandatory]': '1',
                          'field[23][status]': '1',
                          'field[23][position]': '4',
                          'field[23][user_kyc_id]': '7898',
                          'field[23][value]': four?'1':'0',
                          'field[23][required]': 'false',
                          'field[23][invalid]': 'false',
                          'field[24][id]': '157',
                          'field[24][kyc_id]': '3',
                          'field[24][type]': '8',
                          'field[24][info_type]': '20',
                          'field[24][title]': 'هل انت مكلف مهمات عليا في المملكة او دولة اجنبية او مناصب ادارة عليا او وظيفة في المنظمات الدولية؟',
                          'field[24][length]': '',
                          'field[24][mandatory]': '1',
                          'field[24][status]': '1',
                          'field[24][position]': '5',
                          'field[24][user_kyc_id]': '7899',
                          'field[24][value]': five?'1':'0',
                          'field[24][required]': 'false',
                          'field[24][invalid]': 'false',
                          'field[25][id]': '158',
                          'field[25][kyc_id]': '3',
                          'field[25][type]': '8',
                          'field[25][info_type]': '20',
                          'field[25][title]': 'هل لديك صلة قرابة برابطة الدم او الزواج وصولا الى الدرجة الثانية او مقربا من شخص مكلف بمهمات عليا في المملكة او دولة اجنبية او مناصب ادارة عليا او وظيفة في المنظمات الدولية؟',
                          'field[25][length]': '',
                          'field[25][mandatory]': '1',
                          'field[25][status]': '1',
                          'field[25][position]': '6',
                          'field[25][user_kyc_id]': '7900',
                          'field[25][value]': six?'1':'0',
                          'field[25][required]': 'false',
                          'field[25][invalid]': 'false',
                          'field[26][id]': '159',
                          'field[26][kyc_id]': '3',
                          'field[26][type]': '8',
                          'field[26][info_type]': '20',
                          'field[26][title]': 'هل انت المستفيد الحقيقي من الحساب الاستثماري؟',
                          'field[26][length]': '',
                          'field[26][mandatory]': '1',
                          'field[26][status]': '1',
                          'field[26][position]': '7',
                          'field[26][user_kyc_id]': '7901',
                          'field[26][value]': seven?'1':'0',
                          'field[26][required]': 'false',
                          'field[26][invalid]': 'false',
                          'field[27][id]': '160',
                          'field[27][kyc_id]': '3',
                          'field[27][type]': '8',
                          'field[27][info_type]': '20',
                          'field[27][title]': 'هل لديك شهادة التعامل بالأوراق المالية  CME-1 ?',
                          'field[27][length]': '',
                          'field[27][mandatory]': '1',
                          'field[27][status]': '1',
                          'field[27][position]': '8',
                          'field[27][user_kyc_id]': '7902',
                          'field[27][value]': eight?'1':'0',
                          'field[27][required]': 'false',
                          'field[27][invalid]': 'false',
                          'field[28][id]': '165',
                          'field[28][kyc_id]': '13',
                          'field[28][type]': '8',
                          'field[28][info_type]': '25',
                          'field[28][title]': 'الموافقة على اتفاقية الوكالة بالاستثمار',
                          'field[28][length]': '',
                          'field[28][mandatory]': '1',
                          'field[28][status]': '1',
                          'field[28][position]': '1',
                          'field[28][user_kyc_id]': '7904',
                          'field[28][value]': wkaleh?'1':'0',
                          'field[28][required]': 'false',
                          'field[28][invalid]': 'false'
                    }),

                          header: {
                                'Accept': 'application/json, text/plain, */*',
                                'Connection': 'keep-alive',
                          },

              );


  }
}
